/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_image_util_GrabCut */

#ifndef _Included_com_example_image_util_GrabCut
#define _Included_com_example_image_util_GrabCut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_image_util_GrabCut
 * Method:    grabCut
 * Signature: ([IFFIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_image_util_GrabCut_grabCut
  (JNIEnv *, jclass, jintArray, jfloat, jfloat, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
